[deps]
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
MsgPack = "99f44e22-a591-53d1-9472-aa23ef4bd671"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
OpenInterfaces = "07cfd324-e924-40a7-85fa-5e46307e7ad7"
OpenInterfacesImpl = "daff4927-7858-4806-96da-915047fb441c"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[sources]
OpenInterfaces = {path = "lang_julia/OpenInterfaces"}
OpenInterfacesImpl = {path = "lang_julia/OpenInterfacesImpl"}
